#create_clock -period 8.000 -name ClockIn -waveform {0.000 4.000} [get_ports ClockIn]
set_property PACKAGE_PIN K17 [get_ports Clock]
set_property IOSTANDARD LVCMOS33 [get_ports Clock]

set_property PACKAGE_PIN T16 [get_ports {Switches[3]}]
set_property PACKAGE_PIN W13 [get_ports {Switches[2]}]
set_property PACKAGE_PIN P15 [get_ports {Switches[1]}]
set_property PACKAGE_PIN G15 [get_ports {Switches[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Switches[0]}]

set_property PACKAGE_PIN Y16 [get_ports {Buttons[3]}]
set_property PACKAGE_PIN K19 [get_ports {Buttons[2]}]
set_property PACKAGE_PIN K18 [get_ports {Buttons[0]}]
set_property PACKAGE_PIN P16 [get_ports {Buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Buttons[0]}]

set_property PACKAGE_PIN D18 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN G14 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN M15 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN M14 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]